spring:
  data:
    mongodb:
      username: ptatarczuk
      password: haslo123
      host: loocalhost
      port: 27017
      database:  chat_app
      authentication-database: admin

server:
  port: 8088